# Generated by Django 4.0.10 on 2024-02-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('std_number', models.IntegerField()),
                ('teacher', models.CharField(choices=[('ahmadi', 'Ahmadi'), ('abdi', 'Abdi'), ('bahrami', 'Bahrami')], max_length=25)),
            ],
        ),
    ]
